### PR TITLE
Horn branch

### PR DESCRIPTION
**Pull request by thorn18**
See Comments from Commit. Added theme imp+ Menu Bar

### CODE REVIEW

**Comment by thorn18** [comment]
I will look into this and get back to you.

**Comment by thorn18** [comment]
I fixed #1 by commenting it out since there is nothing to do there atm.

#2 i have no idea what is causing that problem. I am using 26, and no there are no local assets.

**Comment by thorn18** [comment]
the findOnPagePreviousDrawable i dont know where that exists, what file is it in.

**Comment by Saerith** [comment]
Thanks, compiles and looks good.

**Pull request merged**
